name: angel_prpl
version: 1.0.0
description: Infrastructure for serving PRPL apps and PWA's in the Angel framework.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  angel_framework: ^2.0.0-alpha
  angel_static: ^2.0.0
  json_annotation: ^1.0.0
  user_agent: ^2.0.0
dev_dependencies:
  angel_test: ^2.0.0-alpha
  build_runner: ^1.0.0
  json_serializable: ^1.0.0
  test: ^1.0.0